# Generated by Django 3.0.6 on 2020-07-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news1', models.CharField(max_length=200)),
                ('subnews1', models.TextField(max_length=100000)),
                ('image1', models.ImageField(upload_to='news/images')),
                ('date1', models.DateField(null=True)),
                ('news2', models.CharField(max_length=200)),
                ('subnews2', models.TextField(max_length=100000)),
                ('image2', models.ImageField(upload_to='news/images')),
                ('date2', models.DateField(null=True)),
                ('news3', models.CharField(max_length=200)),
                ('subnews3', models.TextField(max_length=100000)),
                ('image3', models.ImageField(upload_to='news/images')),
                ('date3', models.DateField(null=True)),
                ('news4', models.CharField(max_length=200)),
                ('subnews4', models.TextField(max_length=100000)),
                ('image4', models.ImageField(upload_to='news/images')),
                ('date4', models.DateField(null=True)),
                ('news5', models.CharField(max_length=200)),
                ('subnews5', models.TextField(max_length=100000)),
                ('image5', models.ImageField(upload_to='news/images')),
                ('date5', models.DateField(null=True)),
                ('news6', models.CharField(max_length=200)),
                ('subnews6', models.TextField(max_length=100000)),
                ('image6', models.ImageField(upload_to='news/images')),
                ('date6', models.DateField(null=True)),
                ('news7', models.CharField(max_length=200)),
                ('subnews7', models.TextField(max_length=100000)),
                ('image7', models.ImageField(upload_to='news/images')),
                ('date7', models.DateField(null=True)),
                ('news8', models.CharField(max_length=200)),
                ('subnews8', models.TextField(max_length=100000)),
                ('image8', models.ImageField(upload_to='news/images')),
                ('date8', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
